SELECT COUNT(*)
FROM CRIME;

SELECT * FROM CRIME LIMIT 10;

SELECT COUNT(*)
FROM CRIME
WHERE ARREST = "TRUE";

SELECT AVG(SAFETY_SCORE)
FROM SCHOOLS;

SELECT * 
FROM CENSUS_DATA 
WHERE COMMUNITY_AREA_NAME LIKE 'B%';

SELECT DISTINCT PRIMARY_TYPE
FROM CRIME
WHERE  LOCATION_DESCRIPTION = 'GAS STATION';

SELECT NAME_OF_SCHOOL
FROM SCHOOLS
WHERE HEALTHY_SCHOOL_CERTIFIED = 'Yes' AND (COMMUNITY_AREA_NUMBER = 10
OR COMMUNITY_AREA_NUMBER = 11
OR COMMUNITY_AREA_NUMBER = 12
OR COMMUNITY_AREA_NUMBER = 13
OR COMMUNITY_AREA_NUMBER = 14
OR COMMUNITY_AREA_NUMBER = 15);

SELECT COMMUNITY_AREA_NAME, AVG(COLLEGE_ENROLLMENT) AS AVERAGE_ENROLLMENT
FROM SCHOOLS
GROUP BY COMMUNITY_AREA_NAME
ORDER BY AVERAGE_ENROLLMENT DESC
LIMIT 5;

SELECT COMMUNITY_AREA_NAME, SAFETY_SCORE
FROM SCHOOLS
WHERE SAFETY_SCORE = (SELECT MIN(SAFETY_SCORE) FROM SCHOOLS);

SELECT COMMUNITY_AREA_NAME, PER_CAPITA_INCOME
FROM CENSUS_DATA
WHERE COMMUNITY_AREA_NUMBER = (SELECT COMMUNITY_AREA_NUMBER 
FROM SCHOOLS
WHERE SAFETY_SCORE = 1);

SELECT NAME_OF_SCHOOL
FROM SCHOOLS
WHERE SAFETY_SCORE < (SELECT AVG(SAFETY_SCORE) FROM SCHOOLS);

SELECT CENSUS_DATA.COMMUNITY_AREA_NAME , CENSUS_DATA.PER_CAPITA_INCOME 
FROM CENSUS_DATA 
INNER JOIN SCHOOLS ON CENSUS_DATA.COMMUNITY_AREA_NUMBER = SCHOOLS.COMMUNITY_AREA_NUMBER 
WHERE SAFETY_SCORE = 1


